# frozen_string_literal: true

$LOAD_PATH.unshift('/Library/RubyMotion/lib')
$LOAD_PATH.unshift('~/.rubymotion/rubymotion-templates')
require 'pry-byebug'

platform = ENV.fetch('platform', 'osx')
require "motion/project/template/#{platform}"

SDK_VERSION = '13.0'
DEPLOYMENT_TARGET = '13.0'

# set these upfront, otherwise other gems using `setup` could cause
# internal validations to fail on incorrect deployment_target/sdk_version
Motion::Project::App.setup do |app|
  app.name = 'linkify-it-rb'
  app.identifier = 'com.motion-gemtest.linkify-it-rb'
  app.sdk_version = ENV.fetch('SDK_VERSION', SDK_VERSION)
  app.deployment_target = ENV.fetch('DEPLOYMENT_TARGET', DEPLOYMENT_TARGET)
end

require 'rubygems'

begin
  require 'bundler'

  testing = true if ARGV.join(' ') =~ /spec/
  testing ? Bundler.require(:default, :spec) : Bundler.require
rescue LoadError
end

require 'motion-expect' if testing

